name:                xdr
version:             0.1.0.0
github:              "unisay/xdr"
license:             BSD3
author:              "Yuriy Lazaryev"
maintainer:          "Yuriy dot Lazaryev at gmail dot com"
copyright:           "2018 Yuriy Lazaryev"

extra-source-files:
- README.md

synopsis:            XDR (RFC 4506) parser
category:            parsing

description:         Please see the README on GitHub at <https://github.com/unisay/xdr#readme>

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- TupleSections
- GeneralizedNewtypeDeriving

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.9 && < 5
- containers
- megaparsec
- protolude
- text

library:
  source-dirs: src

# executables:
#   xdr-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - xdr

tests:
  xdr-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xdr
    - base >= 4.7 && < 5
    - bytestring
    - filepath
    - protolude
    - tasty
    - tasty-golden
    - pretty-show
